apiVersion: v1
kind: Secret
metadata:
  name: medicare-pro-secret
  namespace: default
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: GovardhaniGGSS#12
  DB_NAME: medicare_pro
  JWT_SECRET: 61706123f9a2ef4b968851094aaf71388653df6c6fb21db7730d0df8ce4fe569
